#----------------------------------------------------------
# Theme
#----------------------------------------------------------
[[plugins]]
repo = 'tomasr/molokai'

#----------------------------------------------------------
# LSP
#----------------------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'

[[plugins]]
repo = 'davidhalter/jedi-vim'
